---
- name: add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: config should not be worldwide read- or writeable
  file: path="{{nginx_root_dir}}" mode="o-rw" owner="root" group="root" recurse=yes

- name: Install seboolean dependencies
  yum:
    name:
      - libselinux-python
      - libsemanage-python
  when: ansible_os_family == 'RedHat'

# TODO only do this if the upstream_origin is local
- name: Enable network connections within the machine
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  # https://github.com/ansible/ansible/issues/18692
  when: ansible_os_family == 'RedHat' and ansible_selinux is defined and ansible_selinux != False and ansible_selinux.status == 'enabled'

# manage our own vhost file, because a) the template doesn't work for us, and b) we can use variables from `jdauphant.ssl-certs`
- name: Add vhost config file
  template:
    src: vhost.conf
    dest: "{{ nginx_proxy_vhost_path }}"
    owner: root
    group: root
    mode: 0644
  notify: reload nginx

- name: Check nginx config file is valid
  command: nginx -t

- name: Restart nginx, if necessary
  meta: flush_handlers

- name: Check nginx redirects HTTP to HTTPS
  uri:
    url: http://localhost
    follow_redirects: none
    status_code: 301
  register: http_req
- name: Fail if HTTP doesn't redirect to HTTPS
  fail:
  when: http_req.location != 'https://localhost/'

# TODO Check that nginx is listening on port 443. Not the responsibility of this role to check for a response from the proxied service.
