version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start remote container
          command: |
            docker run \
              -it --privileged -d \
              --name remote \
              --volume /etc/ansible-https-proxy --workdir /etc/ansible-https-proxy \
              geerlingguy/docker-centos7-ansible
      # https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
      - run:
          name: Copy local files
          command: docker cp . remote:/etc/ansible-https-proxy
      - run:
          name: Run tests
          command: docker exec -it remote ./tests/run.sh
