version: 2
jobs:
  test-centos-7:
    # https://circleci.com/docs/2.0/local-jobs/#relative-path-for-working_directory
    working_directory: /etc/gsa.https-proxy
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start remote container
          command: docker run -it --privileged -d --name remote centos/systemd
      - run:
          name: Install Ansible
          command: apk add --update-cache ansible
      - run:
          name: Install Ansible roles
          command: cd tests && ansible-galaxy install -r requirements.yml
      - run:
          name: Run Ansible playbook
          command: cd tests && ansible-playbook -i hosts test.yml
  test-ubuntu-trusty:
    # https://circleci.com/docs/2.0/local-jobs/#relative-path-for-working_directory
    working_directory: /etc/gsa.https-proxy
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start remote container
          command: docker run -it --privileged -d --name remote ubuntu/trusty
      - run:
          name: Install Ansible
          command: apk add --update-cache ansible
      - run:
          name: Install Ansible roles
          command: cd tests && ansible-galaxy install -r requirements.yml
      - run:
          name: Run Ansible playbook
          command: cd tests && ansible-playbook -i hosts test.yml
  test-ubuntu-xenial:
    # https://circleci.com/docs/2.0/local-jobs/#relative-path-for-working_directory
    working_directory: /etc/gsa.https-proxy
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start remote container
          command: docker run -it --privileged -d --name remote ubuntu/xenial
      - run:
          name: Install Ansible
          command: apk add --update-cache ansible
      - run:
          name: Install Ansible roles
          command: cd tests && ansible-galaxy install -r requirements.yml
      - run:
          name: Run Ansible playbook
          command: cd tests && ansible-playbook -i hosts test.yml
workflows:
  version: 2
  build:
    jobs:
      - test-centos-7
      - test-ubuntu-trusty
      - test-ubuntu-xenial