version: 2
jobs:
  build:
    working_directory: /etc/jenkins-deploy
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start remote container
          command: |
            docker run \
              -it --privileged -d \
              --name remote \
              --volume=`pwd`:/etc/ansible-https-proxy --workdir /etc/ansible-https-proxy/tests \
              geerlingguy/docker-centos7-ansible
      - run:
          name: Install roles
          command: |
            docker exec -it remote \
              ansible-galaxy install -r requirements.yml
      - run:
          name: Execute playbook
          command: |
            docker exec -it remote \
              ansible-playbook test.yml
